## 03_ Polars to Numpy and Pandas

In [1]:
import pandas as pd
import numpy as np
import polars as pl

In [2]:
csv_file = "./data/titanic.csv"

In [3]:
df = pl.read_csv(csv_file)
df.head(3)

shape: (3, 12)
┌─────────────┬──────────┬────────┬───────────────────┬───┬───────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str               ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen  ┆ … ┆ A/5 21171 ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Harris            ┆   ┆           ┆         ┆       ┆          │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆           ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina             ┆   ┆ 3101282   ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴───────────────────┴───┴───────────┴─────────┴───────┴──────────┘

### Convert a `DataFrame` to Numpy

In [5]:
arr = df.to_numpy()

print(arr)

[[1 0 3 ... 7.25 None 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 None 'S']
 ...
 [889 0 3 ... 23.45 None 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 None 'Q']]


In [6]:
arr

array([[1, 0, 3, ..., 7.25, None, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, None, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, None, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, None, 'Q']], shape=(891, 12), dtype=object)

In [7]:
# select only int64 dtypes
floats_array = (
    df
    .select(
        pl.col(pl.Float64)
    )
    .to_numpy()
)

floats_array

array([[22.    ,  7.25  ],
       [38.    , 71.2833],
       [26.    ,  7.925 ],
       ...,
       [    nan, 23.45  ],
       [26.    , 30.    ],
       [32.    ,  7.75  ]], shape=(891, 2))

### Convert Numpy to a `DataFrame`

In [9]:
rand_arry = np.random.standard_normal((5, 3)) # 표준정규분포에서 5by3 배열을 반환
(
    pl.DataFrame(
        data = rand_arry
    )
)

shape: (5, 3)
┌───────────┬───────────┬───────────┐
│ column_0  ┆ column_1  ┆ column_2  │
│ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╡
│ -0.813232 ┆ -0.352641 ┆ 1.293133  │
│ 0.004917  ┆ -1.148668 ┆ 1.238054  │
│ -0.997678 ┆ -1.10032  ┆ -0.358986 │
│ -1.30495  ┆ 0.817637  ┆ -0.479864 │
│ 0.521279  ┆ -1.618157 ┆ 0.88571   │
└───────────┴───────────┴───────────┘

In [10]:
rand_arry_2 = np.random.normal(loc = 5, scale = 3, size = (5, 3))
(
    pl.DataFrame(
        data = rand_arry_2
    )
)

shape: (5, 3)
┌──────────┬──────────┬──────────┐
│ column_0 ┆ column_1 ┆ column_2 │
│ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ 7.428179 ┆ 3.283313 ┆ 2.829938 │
│ 5.749804 ┆ 9.286592 ┆ 3.766065 │
│ 5.758608 ┆ 6.604653 ┆ 1.87158  │
│ 9.982422 ┆ 7.314474 ┆ 6.320806 │
│ 7.01874  ┆ 1.528935 ┆ 9.264549 │
└──────────┴──────────┴──────────┘

In [13]:
arr = np.ones(10)
print(arr)

print(pl.Series("a", arr))
(
    print(
        pl.DataFrame(
            data = arr
        )
    )
)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
shape: (10,)
Series: 'a' [f64]
[
	1.0
	1.0
	1.0
	1.0
	1.0
	1.0
	1.0
	1.0
	1.0
	1.0
]
shape: (10, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 1.0      │
│ 1.0      │
│ 1.0      │
│ 1.0      │
│ 1.0      │
│ 1.0      │
│ 1.0      │
│ 1.0      │
│ 1.0      │
│ 1.0      │
└──────────┘


### Convert a `Series` to Numpy

In [14]:
(
    df['Age']
    .head()
    .to_numpy()
)

array([22., 38., 26., 35., 35., nan, 54.,  2., 27., 14.])

In [15]:
(
    df['Age']
    .cast(pl.Int64)
    .head()
    .to_numpy()
)

array([22., 38., 26., 35., 35., nan, 54.,  2., 27., 14.])

### Convert a `DataFrame` to Pandas

In [16]:
(
    df
    .to_pandas()
    .head()
)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  None        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  None        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  None        S

### Calling `pd.DataFrame` on a Polars `DataFrame`

In [17]:
df_pandas = (
    pd.DataFrame(df)
    .head(3)
)

In [18]:
df_pandas

0  1  2                                                  3       4     5   \
0  1  0  3                            Braund, Mr. Owen Harris    male  22.0   
1  2  1  1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2  3  1  3                             Heikkinen, Miss. Laina  female  26.0   

  6  7                 8        9     10 11  
0  1  0         A/5 21171     7.25  None  S  
1  1  0          PC 17599  71.2833   C85  C  
2  0  0  STON/O2. 3101282    7.925  None  S

In [19]:
# Convert pandas df to polars
(
    pl.from_pandas(
        df_pandas
    )
)

shape: (3, 12)
┌─────┬─────┬─────┬─────────────────────────────────┬───┬──────────────────┬─────────┬──────┬─────┐
│ 0   ┆ 1   ┆ 2   ┆ 3                               ┆ … ┆ 8                ┆ 9       ┆ 10   ┆ 11  │
│ --- ┆ --- ┆ --- ┆ ---                             ┆   ┆ ---              ┆ ---     ┆ ---  ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ str                             ┆   ┆ str              ┆ f64     ┆ str  ┆ str │
╞═════╪═════╪═════╪═════════════════════════════════╪═══╪══════════════════╪═════════╪══════╪═════╡
│ 1   ┆ 0   ┆ 3   ┆ Braund, Mr. Owen Harris         ┆ … ┆ A/5 21171        ┆ 7.25    ┆ null ┆ S   │
│ 2   ┆ 1   ┆ 1   ┆ Cumings, Mrs. John Bradley (Fl… ┆ … ┆ PC 17599         ┆ 71.2833 ┆ C85  ┆ C   │
│ 3   ┆ 1   ┆ 3   ┆ Heikkinen, Miss. Laina          ┆ … ┆ STON/O2. 3101282 ┆ 7.925   ┆ null ┆ S   │
└─────┴─────┴─────┴─────────────────────────────────┴───┴──────────────────┴─────────┴──────┴─────┘